export const mockNamespaceMetadata = {
  data: {
    namespace: {
      id: 'gid://gitlab/Group/24',
      linkPaths: {
        groupIssues: '/groups/gitlab-org/-/issues',
        __typename: 'GroupNamespaceLinks',
      },
      __typename: 'Namespace',
    },
  },
};

export const deleteStatusErrorResponse = {
  data: {
    lifecycleUpdate: {
      lifecycle: null,
      errors: ["Cannot delete status 'In progress' because it is in use"],
      __typename: 'LifecycleUpdatePayload',
    },
  },
};

export const mockLifecycles = [
  {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Lifecycle/37',
    name: 'Custom Lifecycle 23',
    defaultOpenStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/165',
      name: 'Karon Homenick',
      __typename: 'WorkItemStatus',
    },
    defaultClosedStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/166',
      name: 'Mignon Kub',
      __typename: 'WorkItemStatus',
    },
    defaultDuplicateStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/167',
      name: 'Ronni Weissnat',
      __typename: 'WorkItemStatus',
    },
    workItemTypes: [],
    statuses: [
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/165',
        name: 'Karon Homenick',
        iconName: 'status-waiting',
        color: '#737278',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/166',
        name: 'Mignon Kub',
        iconName: 'status-success',
        color: '#108548',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/167',
        name: 'Ronni Weissnat',
        iconName: 'status-cancelled',
        color: '#DD2B0E',
        description: null,
        __typename: 'WorkItemStatus',
      },
    ],
    __typename: 'WorkItemLifecycle',
  },
  {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Lifecycle/36',
    name: 'Custom Lifecycle 22',
    defaultOpenStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/162',
      name: 'Fatima Kutch',
      __typename: 'WorkItemStatus',
    },
    defaultClosedStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/163',
      name: 'Catharine Hermann',
      __typename: 'WorkItemStatus',
    },
    defaultDuplicateStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/164',
      name: 'Ester Dietrich',
      __typename: 'WorkItemStatus',
    },
    workItemTypes: [],
    statuses: [
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/162',
        name: 'Fatima Kutch',
        iconName: 'status-waiting',
        color: '#737278',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/163',
        name: 'Catharine Hermann',
        iconName: 'status-success',
        color: '#108548',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/164',
        name: 'Ester Dietrich',
        iconName: 'status-cancelled',
        color: '#DD2B0E',
        description: null,
        __typename: 'WorkItemStatus',
      },
    ],
    __typename: 'WorkItemLifecycle',
  },
  {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Lifecycle/35',
    name: 'Custom Lifecycle 21',
    defaultOpenStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/159',
      name: 'Ella Sauer',
      __typename: 'WorkItemStatus',
    },
    defaultClosedStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/160',
      name: 'Hanna Goyette',
      __typename: 'WorkItemStatus',
    },
    defaultDuplicateStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/161',
      name: 'Vernice Runolfsson',
      __typename: 'WorkItemStatus',
    },
    workItemTypes: [],
    statuses: [
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/159',
        name: 'Ella Sauer',
        iconName: 'status-waiting',
        color: '#737278',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/160',
        name: 'Hanna Goyette',
        iconName: 'status-success',
        color: '#108548',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/161',
        name: 'Vernice Runolfsson',
        iconName: 'status-cancelled',
        color: '#DD2B0E',
        description: null,
        __typename: 'WorkItemStatus',
      },
    ],
    __typename: 'WorkItemLifecycle',
  },
  {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Lifecycle/34',
    name: 'Custom Lifecycle 20',
    defaultOpenStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/156',
      name: 'Ilana Lesch',
      __typename: 'WorkItemStatus',
    },
    defaultClosedStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/157',
      name: 'Debra Rolfson',
      __typename: 'WorkItemStatus',
    },
    defaultDuplicateStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/158',
      name: 'Camilla Stoltenberg',
      __typename: 'WorkItemStatus',
    },
    workItemTypes: [],
    statuses: [
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/156',
        name: 'Ilana Lesch',
        iconName: 'status-waiting',
        color: '#737278',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/157',
        name: 'Debra Rolfson',
        iconName: 'status-success',
        color: '#108548',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/158',
        name: 'Camilla Stoltenberg',
        iconName: 'status-cancelled',
        color: '#DD2B0E',
        description: null,
        __typename: 'WorkItemStatus',
      },
    ],
    __typename: 'WorkItemLifecycle',
  },
  {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Lifecycle/33',
    name: 'Custom Lifecycle 19',
    defaultOpenStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/153',
      name: 'Emily Krajcik',
      __typename: 'WorkItemStatus',
    },
    defaultClosedStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/154',
      name: 'Jong Gorczany',
      __typename: 'WorkItemStatus',
    },
    defaultDuplicateStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/155',
      name: 'Shawn Berge',
      __typename: 'WorkItemStatus',
    },
    workItemTypes: [],
    statuses: [
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/153',
        name: 'Emily Krajcik',
        iconName: 'status-waiting',
        color: '#737278',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/154',
        name: 'Jong Gorczany',
        iconName: 'status-success',
        color: '#108548',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/155',
        name: 'Shawn Berge',
        iconName: 'status-cancelled',
        color: '#DD2B0E',
        description: null,
        __typename: 'WorkItemStatus',
      },
    ],
    __typename: 'WorkItemLifecycle',
  },
  {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Lifecycle/32',
    name: 'Custom Lifecycle 18',
    defaultOpenStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/150',
      name: 'Tiana Okuneva',
      __typename: 'WorkItemStatus',
    },
    defaultClosedStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/151',
      name: 'Ranee Watsica',
      __typename: 'WorkItemStatus',
    },
    defaultDuplicateStatus: {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/152',
      name: 'Dalia Turcotte',
      __typename: 'WorkItemStatus',
    },
    workItemTypes: [],
    statuses: [
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/150',
        name: 'Tiana Okuneva',
        iconName: 'status-waiting',
        color: '#737278',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/151',
        name: 'Ranee Watsica',
        iconName: 'status-success',
        color: '#108548',
        description: null,
        __typename: 'WorkItemStatus',
      },
      {
        id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/152',
        name: 'Dalia Turcotte',
        iconName: 'status-cancelled',
        color: '#DD2B0E',
        description: null,
        __typename: 'WorkItemStatus',
      },
    ],
    __typename: 'WorkItemLifecycle',
  },
];

export const mockDefaultLifecycle = {
  id: 'gid://gitlab/Lifecycle/default',
  name: 'Default',
  defaultOpenStatus: {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/87',
    name: 'To do',
    __typename: 'LocalWorkItemStatus',
  },
  defaultClosedStatus: {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/89',
    name: 'Done',
    __typename: 'LocalWorkItemStatus',
  },
  defaultDuplicateStatus: {
    id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/91',
    name: 'Duplicate',
    __typename: 'LocalWorkItemStatus',
  },
  workItemTypes: [],
  statuses: [
    {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/87',
      name: 'To do',
      iconName: 'status-waiting',
      color: '#737278',
      description: null,
      __typename: 'LocalWorkItemStatus',
    },
    {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/88',
      name: 'In progress',
      iconName: 'status-running',
      color: '#1f75cb',
      description: null,
      __typename: 'LocalWorkItemStatus',
    },
    {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/89',
      name: 'Done',
      iconName: 'status-success',
      color: '#108548',
      description: null,
      __typename: 'LocalWorkItemStatus',
    },
    {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/90',
      name: "Won't do",
      iconName: 'status-cancelled',
      color: '#DD2B0E',
      description: null,
      __typename: 'LocalWorkItemStatus',
    },
    {
      id: 'gid://gitlab/WorkItems::Statuses::Custom::Status/91',
      name: 'Duplicate',
      iconName: 'status-cancelled',
      color: '#DD2B0E',
      description: null,
      __typename: 'LocalWorkItemStatus',
    },
  ],
  __typename: 'LocalLifecycle',
};
