<script>
import { GlButton, GlModal, GlModalDirective, GlSkeletonLoader } from '@gitlab/ui';
import { uniqueId } from 'lodash';
import * as Sentry from '~/sentry/sentry_browser_wrapper';
import { createAlert } from '~/alert';
import { convertToGraphQLId } from '~/graphql_shared/utils';
import { TYPENAME_USER, TYPENAME_MERGE_REQUEST } from '~/graphql_shared/constants';
import aiResponseSubscription from 'ee/graphql_shared/subscriptions/ai_completion_response.subscription.graphql';
import UserFeedback from 'ee/ai/components/user_feedback.vue';
import { fetchPolicies } from '~/lib/graphql';
import { s__, __ } from '~/locale';
import aiActionMutation from 'ee/graphql_shared/mutations/ai_action.mutation.graphql';

export default {
  apollo: {
    $subscribe: {
      // eslint-disable-next-line @gitlab/vue-no-undef-apollo-properties
      aiCompletionResponse: {
        query: aiResponseSubscription,
        fetchPolicy: fetchPolicies.NO_CACHE,
        variables() {
          return {
            resourceId: this.resourceId,
            userId: convertToGraphQLId(TYPENAME_USER, window.gon.current_user_id),
          };
        },
        result({ data }) {
          if (!data.aiCompletionResponse) return;

          const { errors = [], content } = data.aiCompletionResponse;
          let errorMessage;

          if (errors.length || !content) {
            errorMessage =
              errors[0] ||
              s__('AiCommitMessage|An unexpected error has occurred. Please try again.');
            createAlert({ message: errorMessage });
            this.$refs.modal.close();
          } else {
            this.commitMessage = `${content}\n\n-------\n:robot: Commit message generated by GitLab Duo`;
            this.loadingCommitMessage = false;
          }
        },
      },
    },
  },
  components: {
    GlButton,
    GlModal,
    GlSkeletonLoader,
    UserFeedback,
  },
  directives: {
    GlModal: GlModalDirective,
  },
  props: {
    id: {
      type: Number,
      required: true,
    },
    buttonClass: {
      type: String,
      required: false,
      default: null,
    },
  },
  data() {
    return {
      loadingCommitMessage: false,
      commitMessage: '',
    };
  },
  computed: {
    resourceId() {
      return convertToGraphQLId(TYPENAME_MERGE_REQUEST, this.id);
    },
    actionPrimary() {
      return {
        text: __('Insert'),
        attributes: {
          variant: 'confirm',
          disabled: this.loadingCommitMessage,
          'data-testid': 'insert-commit-message',
        },
      };
    },
    modalId() {
      return uniqueId('ai-commit-message');
    },
  },
  methods: {
    triggerAiMutation() {
      this.loadingCommitMessage = true;

      try {
        this.$apollo.mutate({
          mutation: aiActionMutation,
          variables: {
            input: {
              generateCommitMessage: {
                resourceId: this.resourceId,
              },
            },
          },
        });
      } catch (e) {
        Sentry.captureException(e);

        createAlert({
          message: __('There was an error generating commit message.'),
          primaryButton: {
            text: __('Try again'),
            clickHandler: () => this.triggerAiMutation(),
          },
        });
        this.loadingCommitMessage = false;
      }
    },
    insertCommitMessage() {
      this.$emit('update', this.commitMessage);
    },
  },
  modal: {
    actionSecondary: {
      text: __('Cancel'),
      attributes: {
        variant: 'default',
      },
    },
  },
  feedback: {
    eventName: 'generate_commit_message_merge_request',
  },
};
</script>

<template>
  <div>
    <gl-button
      v-gl-modal="modalId"
      icon="tanuki-ai"
      size="small"
      :class="buttonClass"
      data-testid="generate-commit-message"
      @click="triggerAiMutation"
    >
      {{ __('Generate commit message') }}
    </gl-button>
    <gl-modal
      ref="modal"
      :aria-label="__('Commit message')"
      :action-primary="actionPrimary"
      :action-secondary="$options.modal.actionSecondary"
      :modal-id="modalId"
      @primary="insertCommitMessage"
    >
      <template #modal-title>
        {{ __('Commit message') }}
      </template>
      <gl-skeleton-loader v-if="loadingCommitMessage" :width="250" :lines="4" />
      <template v-else>
        <pre
          class="commit-row-description js-toggle-content gl-mb-3 gl-whitespace-pre-wrap"
          data-testid="ai-commit-message-row"
          >{{ commitMessage }}
        </pre>
        <user-feedback :event-name="$options.feedback.eventName" />
        <p>
          {{ __('Commit message generated by GitLab Duo') }}
        </p>
      </template>
    </gl-modal>
  </div>
</template>
