export const mockTimePeriods = [
  {
    key: '5-months-ago',
    label: 'Oct',
    start: new Date('2023-10-01T00:00:00.000Z'),
    end: new Date('2023-10-31T23:59:59.000Z'),
    thClass: 'gl-w-1/10',
    deployment_frequency: {
      identifier: 'deployment_frequency',
      value: 10,
    },
    change_failure_rate: {
      identifier: 'change_failure_rate',
      value: '8.9',
    },
    code_suggestions_usage_rate: {
      identifier: 'code_suggestions_usage_rate',
      value: 0,
      tooltip: '0/0',
    },
  },
  {
    key: '4-months-ago',
    label: 'Nov',
    start: new Date('2023-11-01T00:00:00.000Z'),
    end: new Date('2023-11-30T23:59:59.000Z'),
    thClass: 'gl-w-1/10',
    deployment_frequency: {
      identifier: 'deployment_frequency',
      value: 15,
    },
    change_failure_rate: {
      identifier: 'change_failure_rate',
      value: '5.6',
    },
    code_suggestions_usage_rate: {
      identifier: 'code_suggestions_usage_rate',
      value: 100,
      tooltip: '10/10',
    },
  },
  {
    key: '3-months-ago',
    label: 'Dec',
    start: new Date('2023-12-01T00:00:00.000Z'),
    end: new Date('2023-12-31T23:59:59.000Z'),
    thClass: 'gl-w-1/10',
    deployment_frequency: {
      identifier: 'deployment_frequency',
      value: null,
    },
    change_failure_rate: {
      identifier: 'change_failure_rate',
      value: '0.0',
    },
    code_suggestions_usage_rate: {
      identifier: 'code_suggestions_usage_rate',
      value: 20,
      tooltip: '2/10',
    },
  },
  {
    key: '2-months-ago',
    label: 'Jan',
    start: new Date('2024-01-01T00:00:00.000Z'),
    end: new Date('2024-01-31T23:59:59.000Z'),
    thClass: 'gl-w-1/10',
    deployment_frequency: {
      identifier: 'deployment_frequency',
      value: 30,
    },
    change_failure_rate: {
      identifier: 'change_failure_rate',
      value: null,
    },
    code_suggestions_usage_rate: {
      identifier: 'code_suggestions_usage_rate',
      value: 90.9090909090909,
      tooltip: '10/11',
    },
  },
  {
    key: '1-months-ago',
    label: 'Feb',
    start: new Date('2024-02-01T00:00:00.000Z'),
    end: new Date('2024-02-29T23:59:59.000Z'),
    thClass: 'gl-w-1/10',
    deployment_frequency: {
      identifier: 'deployment_frequency',
      value: '-',
    },
    change_failure_rate: {
      identifier: 'change_failure_rate',
      value: '7.5',
    },
    code_suggestions_usage_rate: {
      identifier: 'code_suggestions_usage_rate',
      value: 50,
      tooltip: '5/10',
    },
  },
  {
    key: 'this-month',
    label: 'Mar',
    start: new Date('2024-03-01T00:00:00.000Z'),
    end: new Date('2024-03-15T13:00:00.000Z'),
    thClass: 'gl-w-1/10',
    deployment_frequency: {
      identifier: 'deployment_frequency',
      value: 30,
    },
    change_failure_rate: {
      identifier: 'change_failure_rate',
      value: '4.0',
    },
    code_suggestions_usage_rate: {
      identifier: 'code_suggestions_usage_rate',
      value: 88.88888888888889,
      tooltip: '8/9',
    },
  },
];

export const mockAiMetricsValues = [
  {
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 20,
  },
  {
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 10,
  },
  {
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 4,
  },
  {
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 20,
  },
  {
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 10,
  },
  {
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 4,
  },
];

export const mockTableValues = [
  {
    deploymentFrequency: 10,
    leadTimeForChanges: 100000,
    timeToRestoreService: 100000,
    changeFailureRate: 0.2,
    cycleTime: 1,
    leadTime: 1,
    issues: 1,
    issuesCompleted: 5,
    deploys: 5,
    medianTimeToMerge: 0.1,
    criticalVulnerabilities: 40,
    highVulnerabilities: 40,
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 20,
    codeSuggestionsAcceptedCount: 3,
    codeSuggestionsShownCount: 15,
    duoChatContributorsCount: 3,
    rootCauseAnalysisUsersCount: 5,
    duoAssignedUsersCount: 15,
    duoUsedCount: 100,
    pipelineCount: 387,
    pipelineSuccessCount: 149,
    pipelineFailedCount: 175,
    pipelineDurationMedian: 150,
  },
  {
    deploymentFrequency: 20,
    leadTimeForChanges: 200000,
    timeToRestoreService: 200000,
    changeFailureRate: 0.4,
    cycleTime: 2,
    leadTime: 2,
    issues: 2,
    issuesCompleted: 10,
    deploys: 10,
    medianTimeToMerge: 0.2,
    criticalVulnerabilities: 20,
    highVulnerabilities: 20,
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 10,
    codeSuggestionsAcceptedCount: 3,
    codeSuggestionsShownCount: 7,
    duoChatContributorsCount: 3,
    rootCauseAnalysisUsersCount: 6,
    duoAssignedUsersCount: 7,
    duoUsedCount: 100,
    pipelineCount: 37,
    pipelineSuccessCount: 49,
    pipelineFailedCount: 15,
    pipelineDurationMedian: 120,
  },
  {
    deploymentFrequency: 40,
    leadTimeForChanges: 400000,
    timeToRestoreService: 400000,
    changeFailureRate: 0.6,
    cycleTime: 4,
    leadTime: 4,
    issues: 4,
    issuesCompleted: 20,
    deploys: 20,
    medianTimeToMerge: 0.3,
    criticalVulnerabilities: 10,
    highVulnerabilities: 10,
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 4,
    codeSuggestionsAcceptedCount: 10,
    codeSuggestionsShownCount: 15,
    duoChatContributorsCount: 10,
    rootCauseAnalysisUsersCount: 11,
    duoAssignedUsersCount: 15,
    duoUsedCount: 100,
    pipelineCount: 27,
    pipelineSuccessCount: 10,
    pipelineFailedCount: 5,
    pipelineDurationMedian: 165,
  },
  {
    deploymentFrequency: 10,
    leadTimeForChanges: 100000,
    timeToRestoreService: 100000,
    changeFailureRate: 0.2,
    cycleTime: 1,
    leadTime: 1,
    issues: 1,
    issuesCompleted: 5,
    deploys: 5,
    medianTimeToMerge: 0.3,
    criticalVulnerabilities: 40,
    highVulnerabilities: 40,
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 20,
    codeSuggestionsAcceptedCount: 9,
    codeSuggestionsShownCount: 18,
    duoChatContributorsCount: 9,
    rootCauseAnalysisUsersCount: 12,
    duoAssignedUsersCount: 18,
    duoUsedCount: 100,
    pipelineCount: 95,
    pipelineSuccessCount: 60,
    pipelineFailedCount: 10,
    pipelineDurationMedian: 90,
  },
  {
    deploymentFrequency: 20,
    leadTimeForChanges: 200000,
    timeToRestoreService: 200000,
    changeFailureRate: 0.4,
    cycleTime: 2,
    leadTime: 2,
    issues: 2,
    issuesCompleted: 10,
    deploys: 10,
    medianTimeToMerge: 0.2,
    criticalVulnerabilities: 20,
    highVulnerabilities: 20,
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 10,
    codeSuggestionsAcceptedCount: 3,
    codeSuggestionsShownCount: 17,
    duoChatContributorsCount: 3,
    rootCauseAnalysisUsersCount: 7,
    duoAssignedUsersCount: 17,
    duoUsedCount: 100,
    pipelineCount: 75,
    pipelineSuccessCount: 18,
    pipelineFailedCount: 15,
    pipelineDurationMedian: 250,
  },
  {
    deploymentFrequency: 40,
    leadTimeForChanges: 400000,
    timeToRestoreService: 400000,
    changeFailureRate: 0.6,
    cycleTime: 4,
    leadTime: 4,
    issues: 4,
    issuesCompleted: 20,
    deploys: 20,
    medianTimeToMerge: 0.1,
    criticalVulnerabilities: 10,
    highVulnerabilities: 10,
    codeSuggestionsContributorsCount: 1,
    codeContributorsCount: 4,
    codeSuggestionsAcceptedCount: 4,
    codeSuggestionsShownCount: 12,
    duoChatContributorsCount: 4,
    rootCauseAnalysisUsersCount: 6,
    duoAssignedUsersCount: 12,
    duoUsedCount: 100,
    pipelineCount: 100,
    pipelineSuccessCount: 50,
    pipelineFailedCount: 25,
    pipelineDurationMedian: 100,
  },
];

export const mockTableLargeValues = [
  {
    deploymentFrequency: 10000,
    leadTimeForChanges: 100000000,
    timeToRestoreService: 100000000,
    changeFailureRate: 0.1,
    cycleTime: 4,
    leadTime: 0,
    issues: 0,
    issuesCompleted: 500,
    deploys: 500,
    medianTimeToMerge: 10,
    criticalVulnerabilities: 4000,
    highVulnerabilities: 4000,
    codeSuggestionsContributorsCount: 500,
    codeContributorsCount: 1000,
    codeSuggestionsAcceptedCount: 800,
    codeSuggestionsShownCount: 2000,
    duoChatContributorsCount: 800,
    rootCauseAnalysisUsersCount: 1000,
    duoAssignedUsersCount: 2000,
    duoUsedCount: 10000,
    pipelineCount: 37000,
    pipelineSuccessCount: 49000,
    pipelineFailedCount: 15000,
    pipelineDurationMedian: 120000,
  },
  {
    deploymentFrequency: 20000,
    leadTimeForChanges: 200000000,
    timeToRestoreService: 200000000,
    changeFailureRate: 0.2,
    cycleTime: 2,
    leadTime: 2,
    issues: 2,
    issuesCompleted: 1000,
    deploys: 1000,
    medianTimeToMerge: 20,
    criticalVulnerabilities: 2000,
    highVulnerabilities: 2000,
    codeSuggestionsContributorsCount: 1000,
    codeContributorsCount: 2000,
    codeSuggestionsAcceptedCount: 1000,
    codeSuggestionsShownCount: 1500,
    duoChatContributorsCount: 1000,
    rootCauseAnalysisUsersCount: 1200,
    duoAssignedUsersCount: 1500,
    duoUsedCount: 10000,
    pipelineCount: 27000,
    pipelineSuccessCount: 29000,
    pipelineFailedCount: 1500,
    pipelineDurationMedian: 1200,
  },
  {
    deploymentFrequency: 40000,
    leadTimeForChanges: 400000000,
    timeToRestoreService: 400000000,
    changeFailureRate: 0.4,
    cycleTime: 1,
    leadTime: 4,
    issues: 4,
    issuesCompleted: 2000,
    deploys: 2000,
    medianTimeToMerge: 30,
    criticalVulnerabilities: 1000,
    highVulnerabilities: 1000,
    codeSuggestionsContributorsCount: 2500,
    codeContributorsCount: 5000,
    codeSuggestionsAcceptedCount: 1200,
    codeSuggestionsShownCount: 2400,
    duoChatContributorsCount: 1200,
    rootCauseAnalysisUsersCount: 2000,
    duoAssignedUsersCount: 2400,
    duoUsedCount: 10000,
    pipelineCount: 45000,
    pipelineSuccessCount: 1000,
    pipelineFailedCount: 100,
    pipelineDurationMedian: 12000,
  },
  {
    deploymentFrequency: 10000,
    leadTimeForChanges: 100000000,
    timeToRestoreService: 100000000,
    changeFailureRate: 0.1,
    cycleTime: 4,
    leadTime: 1,
    issues: 1,
    issuesCompleted: 5000,
    deploys: 5000,
    medianTimeToMerge: 30,
    criticalVulnerabilities: 4000,
    highVulnerabilities: 4000,
    codeSuggestionsContributorsCount: 5000,
    codeContributorsCount: 10000,
    codeSuggestionsAcceptedCount: 2000,
    codeSuggestionsShownCount: 6000,
    duoChatContributorsCount: 2000,
    rootCauseAnalysisUsersCount: 4000,
    duoAssignedUsersCount: 6000,
    duoUsedCount: 10000,
    pipelineCount: 217000,
    pipelineSuccessCount: 129000,
    pipelineFailedCount: 15400,
    pipelineDurationMedian: 5500,
  },
  {
    deploymentFrequency: 20000,
    leadTimeForChanges: 200000000,
    timeToRestoreService: 200000000,
    changeFailureRate: 0.2,
    cycleTime: 2,
    leadTime: 2,
    issues: 2,
    issuesCompleted: 20000,
    deploys: 20000,
    medianTimeToMerge: 20,
    criticalVulnerabilities: 2000,
    highVulnerabilities: 2000,
    codeSuggestionsContributorsCount: 1000,
    codeContributorsCount: 2000,
    codeSuggestionsAcceptedCount: 8000,
    codeSuggestionsShownCount: 9000,
    duoChatContributorsCount: 8000,
    rootCauseAnalysisUsersCount: 7000,
    duoAssignedUsersCount: 9000,
    duoUsedCount: 10000,
    pipelineCount: 52000,
    pipelineSuccessCount: 41000,
    pipelineFailedCount: 1400,
    pipelineDurationMedian: 9300,
  },
  {
    deploymentFrequency: 40,
    leadTimeForChanges: 400000,
    timeToRestoreService: 400000,
    changeFailureRate: 0.4,
    cycleTime: 1,
    leadTime: 4,
    issues: 4,
    issuesCompleted: 5,
    deploys: 5,
    medianTimeToMerge: 10,
    criticalVulnerabilities: 5000,
    highVulnerabilities: 5000,
    codeSuggestionsContributorsCount: 2500,
    codeContributorsCount: 5000,
    codeSuggestionsAcceptedCount: 7000,
    codeSuggestionsShownCount: 8500,
    duoChatContributorsCount: 7000,
    rootCauseAnalysisUsersCount: 8000,
    duoAssignedUsersCount: 8500,
    duoUsedCount: 10000,
    pipelineCount: 720,
    pipelineSuccessCount: 240,
    pipelineFailedCount: 70,
    pipelineDurationMedian: 155,
  },
];

const mockUniformTableRow = (value) => ({
  deploymentFrequency: value,
  changeFailureRate: value,
  leadTimeForChanges: value,
  timeToRestoreService: value,
  cycleTime: value,
  leadTime: value,
  issues: value,
  issuesCompleted: value,
  deploys: value,
  medianTimeToMerge: value,
  criticalVulnerabilities: value,
  highVulnerabilities: value,
  duoChatContributorsCount: value,
  rootCauseAnalysisUsersCount: value,
  duoAssignedUsersCount: value,
  duoUsedCount: value,
  codeSuggestionsContributorsCount: value,
  codeContributorsCount: value,
  codeSuggestionsAcceptedCount: value,
  codeSuggestionsShownCount: value,
  pipelineCount: value,
  pipelineSuccessCount: value,
  pipelineFailedCount: value,
  pipelineDurationMedian: value,
});

export const mockTableBlankValues = [
  mockUniformTableRow('-'),
  mockUniformTableRow('-'),
  mockUniformTableRow('-'),
  mockUniformTableRow('-'),
  mockUniformTableRow('-'),
  mockUniformTableRow('-'),
];

export const mockTableZeroValues = [
  mockUniformTableRow(0),
  mockUniformTableRow(0),
  mockUniformTableRow(0),
  mockUniformTableRow(0),
  mockUniformTableRow(0),
  mockUniformTableRow(0),
];

export const mockTableAndChartValues = [...mockTableValues, ...mockTableValues];

export const mockAiMetricsResponseData = {
  aiMetrics: {
    codeContributorsCount: 8,
    codeSuggestionsContributorsCount: 5,
    codeSuggestionsAcceptedCount: 2,
    codeSuggestionsShownCount: 5,
    duoChatContributorsCount: 5,
    duoAssignedUsersCount: 10,
    duoUsedCount: 3,
    __typename: 'AiMetrics',
  },
  __typename: 'Group',
};

export const mockAiMetricsZeroResponseData = {
  aiMetrics: {
    codeContributorsCount: 0,
    codeSuggestionsContributorsCount: 0,
    codeSuggestionsAcceptedCount: 0,
    codeSuggestionsShownCount: 0,
    duoChatContributorsCount: 0,
    duoAssignedUsersCount: 0,
    duoUsedCount: 0,
    __typename: 'AiMetrics',
  },
  __typename: 'Group',
};

export const mockAiMetricsNullResponseData = {
  aiMetrics: {
    codeContributorsCount: null,
    codeSuggestionsContributorsCount: null,
    codeSuggestionsAcceptedCount: null,
    codeSuggestionsShownCount: null,
    duoChatContributorsCount: null,
    duoAssignedUsersCount: null,
    duoUsedCount: null,
    __typename: 'AiMetrics',
  },
  __typename: 'Group',
};
