# frozen_string_literal: true

RSpec.shared_examples 'AI catalog version definition field' do
  context 'when yaml_definition is present' do
    before do
      item.latest_version.definition['yaml_definition'] = 'test'
      item.latest_version.save!
    end

    it 'returns the yaml_definition' do
      expect(returned_definition).to match('test')
    end
  end
end

RSpec.shared_examples 'AI catalog version definition field with yaml_definition not present' do
  context 'when yaml_definition is not present' do
    before do
      item.latest_version.definition.delete('yaml_definition')
      item.latest_version.save!
    end

    it 'returns the definition generated by converting the definition to YAML' do
      expect(YAML.load(returned_definition)).to match(item.latest_version.definition)
    end
  end
end
