export const expectedAttributes = [
  {
    id: 3,
    categoryId: 11,
    name: 'Capital Commit',
    description:
      'An enterprise lending solution that manages the complete lifecycle of commercial loans from application to disbursement.',
    color: '#EC6337',
    projectCount: 2,
    category: {
      id: 11,
      name: 'Application',
      description: 'Categorize projects by application type and technology stack.',
      multipleSelection: true,
      canEditCategory: false,
      canEditAttributes: true,
      attributeCount: 8,
    },
  },
  {
    id: 4,
    categoryId: 11,
    name: 'Deposit Source',
    description:
      'A savings account management system that handles interest calculations, automatic transfers, and customer-facing deposit operations.',
    color: '#613CB1',
    projectCount: 59,
    category: {
      id: 11,
      name: 'Application',
      description: 'Categorize projects by application type and technology stack.',
      multipleSelection: true,
      canEditCategory: false,
      canEditAttributes: true,
      attributeCount: 8,
    },
  },
  {
    id: 11,
    categoryId: 12,
    name: 'Business Operational',
    description: 'Standard operational systems',
    color: '#CF9846',
    projectCount: 2,
    category: {
      id: 12,
      name: 'Business Impact',
      description: 'Classify projects by their importance to business operations.',
      multipleSelection: false,
      canEditCategory: false,
      canEditAttributes: false,
      attributeCount: 5,
    },
  },
  {
    id: 15,
    categoryId: 15,
    name: 'Singapore::Singapore',
    description: 'Asia-Pacific regional office covering Southeast Asian operations.',
    color: '#D3875B',
    projectCount: 31,
    category: {
      id: 15,
      name: 'Location',
      description: 'Track system hosting locations and geographic deployment.',
      multipleSelection: false,
      canEditCategory: true,
      canEditAttributes: true,
      attributeCount: 7,
    },
  },
];
